# Generated by Django 3.0.6 on 2020-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0003_userdatabase_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='email_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='instaram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
