# Generated by Django 3.0.6 on 2020-06-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0004_auto_20200615_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='Connect.UserDatabase')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Connect.UserDatabase')),
            ],
        ),
    ]
