# Generated by Django 3.0.6 on 2020-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0008_company_model_map_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='mapurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
